name: GitHub Actions Quickstart

on: 
  push:
    jobs:
      Explore-GitHub-Actions:
       runs-on: ubuntu-latest
       steps:
        - run: echo "これは ${{ github.event_name}} によってトリガーされました。"
        - run: echo "現在 ${{ runner.os }} 上で動作しています。"
        - run: echo "対象は Repository -> ${{ github.repository }} Brach -> ${{ github.ref }} です。"
        - name: Checkout
        uses: actions/checkout@v2
        - name: Listing repository 日本語を使ってみる
        run: |
            ls ${{ github.workspace }}
        - run: echo "Job status -> ${{ job.status }}"
  workflow_dispatch:
    inputs:
      username:
        description: "User Name"
        required: true
        default: "hogehoge"
        type: string
  jobs:
    print-name:
      runs-on: ubuntu-latest
      steps:
        - run: echo "My name is ${{ github.event.inputs.username }}"