name: GitHub Actions Quickstart

on: 
  workflow_dispatch:
    inputs:
      username:
        description: "User Name"
        required: true
        default: "hogehoge"
        type: string
  jobs:
    print-name:
      runs-on: ubuntu-latest
      steps:
        - run: echo "My name is ${{ github.event.inputs.username }}"